sudo: required

language: go

go:
  - 1.7.x

services:
  - docker

before_install:
  - make docker_setup
  - docker ps -a

script: go test -v ./...

after_success:
  - bash <(curl -s https://codecov.io/bash)
